name: CI

on: 
  pull_request:
  push:
    branches:
      - master

env:
  # Used in Makefile
  ON_GITHUB: 1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Pull test container
      run: make docker-pull

    - name: pytest + ruff + mypy
      run: make test

    - name: examples
      run: |
        pip install -e .
        python ./examples/txn_size.py
